options:
  port:
    default: 3000
    type: int
  app-id:
    type: string
  private-key:
    type: string
  webhook-secret:
    type: string
  jira-instance:
    type: string
  jira-username:
    type: string
  jira-token:
    type: string
  bot-config:
    default: ""
    type: string
  bot-name:
    default: ""
    type: string
